### ISSUE TITLE
Top divider is broken when scrolled while containing a paper-menu component

### ISSUE THREAD

**Issue by bpinney** [PolymerElements/paper-dialog-scrollable#11]
![screen shot 2015-06-19 at 16 54 14](https://cloud.githubusercontent.com/assets/2642102/8262973/d2bdba18-16a4-11e5-8bff-9e1254856126.png)

Expected result: 

Divider is solid across the element.
![screen shot 2015-06-19 at 16 54 53](https://cloud.githubusercontent.com/assets/2642102/8263059/80f027f6-16a5-11e5-9bc9-37c811a4fe81.png)

**Comment by notwaldorf** [comment]
Does this repro with `paper-listbox` instead of `paper-menu`? That element is a faster version of paper-menu, with a slightly different style api that might fix this bug

**Comment by bpinney** [comment]
Yes, the issue is still present with `paper-listbox` as opposed to `paper-menu`.

**Comment by valdrinkoshi** [comment]
~~issue on `paper-dialog-scrollable` which should set `z-index` for the dividers so that they render on top~~
This has been fixed with https://github.com/PolymerElements/paper-dialog-scrollable/commit/ba973d2ddef8042ce08329be29efe723061ab68a
http://jsbin.com/caruri/1/edit?html,output
