### ISSUE TITLE
Uncaught TypeError: Cannot set property 'sizingTarget' of null

### ISSUE THREAD

**Issue by alexhuot1** [PolymerElements/paper-dialog-scrollable#14]
Hi,

I get this error log in my console for every instance of paper-dialog/paper-dialog-scrollable use in my app.

Uncaught TypeError: Cannot set property 'sizingTarget' of nullPolymer.attached @ paper-dialog-scrollable.html:125

It's important that you know that i use Meteor, therefore Blaze to render my page. So to be able to use Polymer i'm using shadow dom.

I think it's related to re-rendering process since it's not logged if i do a full page refresh.

I know it's not your job the make this work with Blaze, but do you have any idea of what can cause this issue.

Thanks a lot.

**Comment by Artur-** [comment]
Possibly the same as #22

**Comment by valdrinkoshi** [comment]
This should have been fixed with https://github.com/PolymerElements/paper-dialog-scrollable/commit/ba973d2ddef8042ce08329be29efe723061ab68a
Feel free to reopen if the problem persists.
