### ISSUE TITLE
Move paper-dialog-scrollable inside paper-dialog?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-dialog-scrollable#15]
This element describes "_A scrollable area used inside the material design dialog_".
Then, if `paper-dialog-scrollable` needs the `paper-dialog`... Why not move `paper-dialog-scrollable` element inside `paper-dialog` element? Like `paper-tabs` and `paper-tab`.

On the other hand, if `paper-dialog-scrollable` can be used without the `paper-dialog`... Maybe is a good idea change the name to, for example, `paper-scrollable`.

What do you think? :smiley:

**Comment by miztroh-zz** [comment]
+1

**Comment by motss** [comment]
:+1:

**Comment by notwaldorf** [comment]
Yeah, that wouldn't be a terrible idea. I've made a note of it in a tracking document :)

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
