### ISSUE TITLE
Buttons don't show on modal dialog on iPhone

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-dialog-scrollable#16]
In a `<paper-drawer-panel>`, at the very least.

See:

![img_8219](https://cloud.githubusercontent.com/assets/165937/10718487/148571b6-7b31-11e5-8b4e-fd11790d92db.PNG)

vs.

![screenshot_2015-10-25-155318](https://cloud.githubusercontent.com/assets/165937/10718500/a8124cec-7b31-11e5-9aa8-586a91c8af58.png)

vs.

![image](https://cloud.githubusercontent.com/assets/165937/10718478/cfa47128-7b30-11e5-9bd8-8dd34471d54b.png)

See live site (hidden page):
http://papayapythons.com/outreach.php

This is ignoring the various bugginess from `paper-dialog` on mobile in general (like the off center, narrow width, and the fact that the scrollable scrolls the buttons a bit)

**Comment by tigerhawkvok** [comment]
A workaround for this is to apply `overflow-y: scroll` on the `paper-dialog`.

So, in my helper function (because Safari is generally a hellball), I include:

``` coffee
    try
      # Safari is stupid and like to throw an error. Presumably
      # it's VERY slow about creating the element.
      $(selector).get(0).open()
      ###
      # Safari dialogs have weird scroll interception.
      # See:
      #
      # https://stackoverflow.com/questions/9280258/prevent-body-scrolling-but-allow-overlay-scrolling
      # https://stackoverflow.com/questions/23885894/ios7-scroll-in-fixed-overlay-causes-body-scrolling
      # https://github.com/twbs/bootstrap/issues/9315
      # http://runastartup.com/overlay-scrolling-issues-on-iphone-ipad/
      #
      # So we'll throw overflow-y on the dialog.
      ###
      try
        console.warn "We're using iOS! We need to fix the scroll behaviour."
        b = new WhichBrowser()
        if b.os.name is "iOS"
          $(selector).css "overflow-y", "scroll"
      if typeof callback is "function"
        callback()
```

(the `catch` to this delays and re-runs the helper -- it usually takes safari ~300ms to be able to open the dialog). This uses the [WhichBrowser](https://github.com/WhichBrowser/Parser) library.

**Comment by valdrinkoshi** [comment]
Hi @tigerhawkvok, ~~you can use the `--layout-flex` mixin on `paper-dialog-scrollable` to achieve the correct rendering 
http://jsbin.com/cuguko/4/edit?html,output~~
Update: don't set the `min-height` since `paper-dialog` handles the resizing of `paper-dialog-scrollable`
![scrollable](https://cloud.githubusercontent.com/assets/6173664/12150056/2d3ca79c-b45c-11e5-97a6-b17447c47743.gif)

~~@cdata, shouldn't `paper-dialog-scrollable` apply this mixin by default on `:host`? WDYT?~~

**Comment by valdrinkoshi** [comment]
After further tests, I realized that the problem is when we set a `min-height` to `paper-dialog-scrollable`.
`paper-dialog` handles the resizing of `paper-dialog-scrollable`, so no need to set the min-height.
