### ISSUE TITLE
paper-dialog-scrollable cannot be created using Javascript

### ISSUE THREAD

**Issue by Artur-** [PolymerElements/paper-dialog-scrollable#22]
```
var l = document.createElement("link");
l.setAttribute("href","https://rawgit.com/Download/polymer-cdn/master/lib/paper-dialog/paper-dialog.html");
l.setAttribute("rel","import");
document.head.appendChild(l);

var l = document.createElement("link");
l.setAttribute("href","https://rawgit.com/Download/polymer-cdn/master/lib/paper-dialog-scrollable/paper-dialog-scrollable.html");
l.setAttribute("rel","import");
document.head.appendChild(l);
```

```
var pd = document.createElement("paper-dialog");
var pds = document.createElement("paper-dialog-scrollable");

pd.appendChild(document.createElement("h2"))
pd.appendChild(pds)


document.body.innerHTML = "";
document.body.appendChild(pd);
```

Causes `Uncaught TypeError: Cannot set property 'sizingTarget' of null` in paper-dialog-scrollable attached because the dialogElement value has apparently been fetched and cached in the ready phase, which happens before attach and when parentNode is null.

**Comment by KrauseStefan** [comment]
+1
The same error is triggered by the way Angular 2 adds content to the dom.

**Comment by cstavro** [comment]
+1
Just ran into this with Angular2 as well.

**Comment by valdrinkoshi** [comment]
Could not reproduce the issue http://jsbin.com/zoxube/3/edit?html,output

**Comment by valdrinkoshi** [comment]
@Artur- @cstavro @KrauseStefan please let me know if the issue still persists (if possible with some code snippet), I'll reopen the issue :)

**Comment by Artur-** [comment]
http://jsbin.com/bopirunuca/1/edit?html,output

**Comment by cstavro** [comment]
@Artur- that snippet reproduces the issue on my end as well.

**Comment by valdrinkoshi** [comment]
same here, reopening

**Comment by valdrinkoshi** [comment]
This gets solved by setting the property `dialogElement`
http://jsbin.com/zitugut/1/edit?html,output
I'll provide the fix in a PR shortly
