### ISSUE TITLE
Scrolling to top or bottom causes unwanted window scroll

### ISSUE THREAD

**Issue by wswoodruff** [PolymerElements/paper-dialog-scrollable#23]
I wish the window wouldn't scroll behind the paper dialog when you scroll beyond the top or bottom of a paper-dialog-scrollable area; any way to prevent this?

**Comment by valdrinkoshi** [comment]
`paper-dialog` extends `paper-dialog-behavior` which extends `iron-overlay-behavior`.
I believe this should be an enhancement of `iron-overlay-behavior`, which should prevent the scrolling of the content behind.

**Comment by wswoodruff** [comment]
Ok, I will take a look over there
