### ISSUE TITLE
Absolute elements calculating position/height based on host instead of scrolling div

### ISSUE THREAD

**Issue by pengying** [PolymerElements/paper-dialog-scrollable#49]
### Description

Expected:
Absolute element calculates position/height relative to inner div:
<img width="1456" alt="screen shot 2016-04-11 at 6 33 23 pm" src="https://cloud.githubusercontent.com/assets/495700/14447381/fb893e78-0013-11e6-99dc-7aad875b6f37.png">

Actual:
Absolute element calculate position/height relative to paper-dialog-scrollable
<img width="1466" alt="screen shot 2016-04-11 at 6 31 55 pm" src="https://cloud.githubusercontent.com/assets/495700/14447384/0aaf8eac-0014-11e6-95ad-ecbe8ee651f4.png">

### Live Demo

N/A
### Steps to reproduce

Add position:relative to #scrollable

### Browsers Affected

- [X ] Chrome
- [X ] Firefox
- [X ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
@pengying in this test I don't see the issue you describe http://jsbin.com/bibisey/2/edit?html,output
Can you provide an example showing the issue?

**Comment by pengying** [comment]
Yeah it's actually not modifying the size of the dialog, it's overflowing it. 

Whoa that's how you get elements working in jsbin.
http://jsbin.com/fiforizijo/edit?html,output

**Comment by valdrinkoshi** [comment]
@pengying all you need is apply the mixin :)
http://jsbin.com/pugukiw/2/edit?html,output
I think your use case is specific (not everyone sets content to `position: absolute`), so there's no need for `.scrollable` to have `position: relative`. Closing this

**Comment by pengying** [comment]
Ah yeah you're right.
