### ISSUE TITLE
paper-dialog-scrollable only works if it's the direct child of paper-dialog

### ISSUE THREAD

**Issue by fejesjoco** [PolymerElements/paper-dialog-scrollable#53]
Because it expects parentNode to be a paper-dialog: https://github.com/PolymerElements/paper-dialog-scrollable/blob/b40b9c5/paper-dialog-scrollable.html#L170

If it's not true, it fails (dialog collapses into a singularity).

I'd like to have an element like this:

```
<paper-dialog>
  <form>
    stuff
    <paper-dialog-scrollable>more stuff</paper-dialog-scrollable>
    <input type="submit">
  </form>
</paper-dialog>
```

The correct behavior would be to find the closest parent that is a paper-dialog or has the PaperDialogBehaviorImpl behavior .

**Comment by ccjmne** [comment]
Seems sensible to me too!

In the meantime you can set your `paper-dialog-scrollable`'s `dialogElement` property to the right node yourself, programatically:

```
ready: function () {
  this.$$('#my-dialog paper-dialog-scrollable').dialogElement = this.$['my-dialog'];
}
```

You'll probably wanna include some negative margins on that scrollable though, to account for its parent `form`'s.  
For instance, would your form be a `<form is="iron-form">` (wink wink), consider the following addition to your style:

```
paper-dialog#my-dialog paper-dialog-scrollable {
  margin: 0 -24px;
}
```

## 

Alternatively, we (you?) could format that issue according to [the contribution recommendations](https://github.com/PolymerElements/paper-dialog-scrollable/blob/master/CONTRIBUTING.md) and submit a Pull request with the enhancement. 🙂

**Comment by valdrinkoshi** [comment]
You can set the `dialog-element` property of to anything, e.g. http://jsbin.com/fecihox/2/edit?html,output

``` html
<dom-module id="x-sample">
  <template>
    <paper-dialog id="dialog" opened>
      <form>
        stuff 
        <paper-dialog-scrollable dialog-element="[[dialogElement]]">
          <content></content>
        </paper-dialog-scrollable>
        <input type="submit">
      </form>
    </paper-dialog>
  </template>
  <script>
    Polymer({
      is: 'x-sample',
      properties: {
        dialogElement: {
          type: Object,
          value: function(){
            return this.$.dialog;
          }
        }
      }
    });
  </script>
</dom-module>
```
