### ISSUE TITLE
paper-dialog {max-height: foo} breaks paper-dialog-scrollable

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/paper-dialog-scrollable#55]
### Description

Adding `max-height` CSS property to `paper-dialog` breaks `paper-dialog-scrollable`.
### Expected outcome

To see scrolling behavior in `paper-dialog-scrollable`.
### Actual outcome

Text overflows `paper-dialog` element and no scrolling behavior occurs.
### Live Demo

http://jsbin.com/gamulisiva/1/edit?html,console,output
### Steps to reproduce
1. Click button labeled <kbd>Open</kbd>.
2. Notice text overflows dialog and does not scroll.
3. Delete the following: `max-height: 80vh;`
4. Click button labeled <kbd>Open</kbd>.
5. Notice text does not overflow and dialog scrolls as expected.
### Browsers Affected

- [X] Chrome

Issue has been cross posted here --> https://github.com/PolymerElements/paper-dialog/issues/130

**Comment by valdrinkoshi** [comment]
Duplicate, will continue discussing in PolymerElements/paper-dialog#130 👌
