### ISSUE TITLE
1.1.5 release tag missing a v

### ISSUE THREAD

**Issue by jart** [PolymerElements/paper-dialog-scrollable#57]
Every polymer project puts a 'v' in the tag name, including this one. But in the recent 1.1.5 release, it was missing. Just thought you might want to know :3

**Comment by valdrinkoshi** [comment]
Yeah, unfortunately not much that can be done at this point, as that version is already published and bower handles the missing "v". Will close this, let me know if this is creating particular issues & your use case, so I can help if needed :)
