### ISSUE TITLE
_ensureTarget not always finds the behaviors

### ISSUE THREAD

**Issue by fincha** [PolymerElements/paper-dialog-scrollable#63]
### Description
in our current custom dialog component we implement the `Polymer.PaperDialogBehavior` but the paper-dialog-scrollable wasn't able to locate the behavior, only in the host property

our current implementation:

```
<paper-dialog-scrollable role="document">
    <slot name="dialog-content"></slot>
</paper-dialog-scrollable>
```
the JS code

```
ready: function () {
    this.$$('paper-dialog-scrollable').dialogElement = this;
}
```

the problem is in this function:

```
    _ensureTarget: function () {
      // read parentNode on attached because if dynamically created,
      // parentNode will be null on creation.
      this.dialogElement = this.dialogElement || Polymer.dom(this).parentNode;
      // Check if parent implements paper-dialog-behavior. If not, fit scrollTarget to host.
      if (this.dialogElement && this.dialogElement.behaviors &&
          this.dialogElement.behaviors.indexOf(Polymer.PaperDialogBehaviorImpl) >= 0) {
        this.dialogElement.sizingTarget = this.scrollTarget;
        this.scrollTarget.classList.remove('fit');
      } else if (this.dialogElement) {
        this.scrollTarget.classList.add('fit');
      }
    }
```
if you consol.log the `this.dialogElement` you will see the #shadow-root element, and this element does not has the behaviors, but if you try to look up them in the this.dialogElement.host - they are there... I believe this is most clear solution, instead of checking for root.

### Expected outcome

`this.dialogElement` resolves to be the element 'custom-dialog`

### Actual outcome

`this.dialogElement` resolves to be #shadow-root

### Live Demo
n/a

### Browsers Affected

- [x ] Chrome

only browser I tested

**Comment by valdrinkoshi** [comment]
@fincha yes, currently paper-dialog-scrollable supports being added only in the light dom, whereas in your case you're adding it in the shadow dom of your custom dialog.
