### ISSUE TITLE
Divider not shown when dynamically adding content

### ISSUE THREAD

**Issue by LarsDenBakker** [PolymerElements/paper-dialog-scrollable#66]
### Description
The scrollable divider state is initially calculated on attached, and then for every user scroll. When content is added after the scrollable was instantiated, the bottom/top divider is not shown until the user scrolls. This prevents an indication of the content being scrollable. This mostly happens when using XHR to fetch some data, and then a dom-repeater to display the content.

### Expected outcome

The border is shown after dom-content changes, or a public method is exposed to notify the scrollable of changing content.

### Actual outcome

The border is not shown after content was added dynamically.

### Steps to reproduce

1. Create a paper dialog with a scrollable inside it.
2. Create a dom-repeat with an items data binding.
3. Add some items after a delay
4. See that there is no bottom border. Scroll, then see the border appear.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by LarsDenBakker** [comment]
See https://github.com/PolymerElements/paper-dialog-scrollable/pull/67 and https://github.com/PolymerElements/paper-dialog-scrollable/pull/68 for two possible solutions.

Looking forward to what you guys think.

**Comment by valdrinkoshi** [comment]
Hi @LarsDenBakker, thanks for reporting this!
It is tricky to know "when" to update those classes; usually `paper-dialog-scrollable` is used into a `paper-dialog` which might be closed while mutations are happening, hence having a mutation observer wouldn't be enough, as we would get scrollTop/Left = 0.
Exposing a public method to update the scroll state would drop this duty to the user, as she would have to do those checks anyways...this could technically be achieved today by firing a `scroll` event on `scrollTarget` to achieve the desired result:
```html
<paper-dialog id="dialog">
   <paper-dialog-scrollable id="scrollable"></paper-dialog-scrollable>
</paper-dialog>
```
```js
// Dynamically update the content of paper-dialog-scrollable
scrollable.appendChild(newChild);
if (dialog.opened) {
  // Fake a scroll so scroll state gets updated.
  scrollable.scrollTarget.dispatchEvent(new CustomEvent('scroll'));
}
```
With `updateScrollState`, this code wouldn't change much: 
```js
// Dynamically update the content of paper-dialog-scrollable
scrollable.appendChild(newChild);
if (dialog.opened) {
  scrollable.updateScrollState();
}
```

**Comment by LarsDenBakker** [comment]
Good point on the closed state of a dialog, that would indeed be an issue. 

Leaving it up to the user seems like the most sensible option then, thought I would prefer a more semantic way of notifying the scrollable. Throwing an event feels a bit off.

**Comment by valdrinkoshi** [comment]
Yeah, especially if we go with the mantra "events go up, properties go down".
In this case we want to set properties on the scrollable, so would be better to have a method rather than firing a "fake" event 👌  Let's go with #67 then!

**Comment by valdrinkoshi** [comment]
#67 merged, closing this
