### ISSUE TITLE
Active Button forces paper-dialog-scrollable to be scrolled to the bottom

### ISSUE THREAD

**Issue by contis2908** [PolymerElements/paper-dialog-scrollable#70]
### Description

The active attribute on the buttons inside the paper-dialog-scrollable forces the content to be scrolled to the bottom when opening the dialog window.

### Expected outcome
On open() the paper-dialog-scrollable should be sowing the top of the text (it's content)

### Actual outcome
The content is scrolled to the bottom where the buttons are places.

### Steps to reproduce
```html
<paper-dialog>
  <h2>Header</h2>
  <paper-dialog-scrollable>
    Enough content is needed in here to create a scroll on your device
  </paper-dialog-scrollable>
  <div class="buttons">
    <paper-button dialog-confirm autofocus>Accept</paper-button>
  </div>
</paper-dialog>
```
### Browsers Affected and tested
- Chrome

**Comment by valdrinkoshi** [comment]
Cannot repro
![scrollable-ok](https://cloud.githubusercontent.com/assets/6173664/26693783/3e36a088-46ba-11e7-813e-fbb28e1e8ccc.gif)
